// Mock data for the prototype
window.MOCK = (() => {
  const banks = [
    {
      id: "bbva",
      name: "BBVA",
      accountLabel: "Cuenta Online",
      last4: "4821",
      balance: 4820.45,
      color: "#004481",
      logoBg: "#004481",
      logoText: "BBVA",
      type: "checking",
      delta: 2.1,
    },
    {
      id: "santander",
      name: "Santander",
      accountLabel: "1|2|3 Smart",
      last4: "7302",
      balance: 12340.8,
      color: "#EC0000",
      logoBg: "#EC0000",
      logoText: "●",
      type: "savings",
      delta: 4.3,
    },
    {
      id: "caixabank",
      name: "CaixaBank",
      accountLabel: "Day to Day",
      last4: "1193",
      balance: 2158.12,
      color: "#007EAE",
      logoBg: "#007EAE",
      logoText: "★",
      type: "checking",
      delta: -1.2,
    },
    {
      id: "ing",
      name: "ING",
      accountLabel: "Orange Account",
      last4: "9841",
      balance: 8640.0,
      color: "#FF6200",
      logoBg: "#FF6200",
      logoText: "ING",
      type: "savings",
      delta: 0.8,
    },
    {
      id: "revolut",
      name: "Revolut",
      accountLabel: "Metal",
      last4: "2234",
      balance: 1920.55,
      color: "#0075EB",
      logoBg: "#0C1014",
      logoText: "R",
      type: "checking",
      delta: 8.4,
    },
  ];

  const availableBanks = [
    { id: "sabadell", name: "Banco Sabadell", color: "#004A98" },
    { id: "bankinter", name: "Bankinter", color: "#FF7B00" },
    { id: "openbank", name: "Openbank", color: "#EC0000" },
    { id: "n26", name: "N26", color: "#36A18B" },
    { id: "wise", name: "Wise", color: "#9FE870" },
    { id: "abanca", name: "Abanca", color: "#00A9E0" },
    { id: "unicaja", name: "Unicaja", color: "#00833B" },
    { id: "kutxabank", name: "Kutxabank", color: "#00AEEF" },
  ];

  const categories = [
    {
      id: "groceries",
      name: "Groceries",
      icon: "shopping-cart",
      color: "#22C55E",
      budget: 600,
      spent: 432.1,
    },
    {
      id: "dining",
      name: "Dining out",
      icon: "utensils",
      color: "#F97316",
      budget: 300,
      spent: 287.4,
    },
    { id: "transport", name: "Transport", icon: "car", color: "#3B82F6", budget: 200, spent: 94.2 },
    {
      id: "rent",
      name: "Rent & utilities",
      icon: "home",
      color: "#8B5CF6",
      budget: 1400,
      spent: 1400.0,
    },
    {
      id: "subscriptions",
      name: "Subscriptions",
      icon: "repeat",
      color: "#EC4899",
      budget: 80,
      spent: 112.5,
    },
    {
      id: "entertainment",
      name: "Entertainment",
      icon: "film",
      color: "#EAB308",
      budget: 150,
      spent: 68.9,
    },
    {
      id: "health",
      name: "Health & fitness",
      icon: "heart-pulse",
      color: "#EF4444",
      budget: 120,
      spent: 45.0,
    },
    {
      id: "shopping",
      name: "Shopping",
      icon: "shopping-bag",
      color: "#06B6D4",
      budget: 250,
      spent: 384.12,
    },
    {
      id: "savings",
      name: "Savings",
      icon: "piggy-bank",
      color: "#10B981",
      budget: 800,
      spent: 800.0,
    },
  ];

  const transactions = [
    {
      id: "t1",
      date: "2026-04-19",
      merchant: "Mercadona",
      category: "groceries",
      bank: "bbva",
      amount: -67.4,
      note: "Weekly shop",
    },
    {
      id: "t2",
      date: "2026-04-19",
      merchant: "Netflix",
      category: "subscriptions",
      bank: "revolut",
      amount: -13.99,
      note: "Monthly",
    },
    {
      id: "t3",
      date: "2026-04-18",
      merchant: "Cabify",
      category: "transport",
      bank: "bbva",
      amount: -12.5,
      note: "",
    },
    {
      id: "t4",
      date: "2026-04-18",
      merchant: "Zara",
      category: "shopping",
      bank: "santander",
      amount: -89.95,
      note: "Spring jacket",
    },
    {
      id: "t5",
      date: "2026-04-17",
      merchant: "Spotify",
      category: "subscriptions",
      bank: "revolut",
      amount: -10.99,
      note: "Family plan",
    },
    {
      id: "t6",
      date: "2026-04-17",
      merchant: "Employer Corp",
      category: null,
      bank: "santander",
      amount: 3240.0,
      note: "Salary · April",
      income: true,
    },
    {
      id: "t7",
      date: "2026-04-16",
      merchant: "Lidl",
      category: "groceries",
      bank: "caixabank",
      amount: -34.18,
      note: "",
    },
    {
      id: "t8",
      date: "2026-04-16",
      merchant: "Bar Antonio",
      category: "dining",
      bank: "bbva",
      amount: -28.4,
      note: "Friday dinner",
    },
    {
      id: "t9",
      date: "2026-04-15",
      merchant: "EMT Madrid",
      category: "transport",
      bank: "bbva",
      amount: -21.8,
      note: "Monthly pass",
    },
    {
      id: "t10",
      date: "2026-04-14",
      merchant: "Iberdrola",
      category: "rent",
      bank: "caixabank",
      amount: -84.2,
      note: "Electricity",
    },
    {
      id: "t11",
      date: "2026-04-14",
      merchant: "Amazon",
      category: "shopping",
      bank: "revolut",
      amount: -42.99,
      note: "Desk lamp",
    },
    {
      id: "t12",
      date: "2026-04-13",
      merchant: "Starbucks",
      category: "dining",
      bank: "bbva",
      amount: -6.4,
      note: "",
    },
    {
      id: "t13",
      date: "2026-04-12",
      merchant: "Glovo",
      category: "dining",
      bank: "bbva",
      amount: -19.8,
      note: "Sunday lunch",
    },
    {
      id: "t14",
      date: "2026-04-11",
      merchant: "Apple Music",
      category: "subscriptions",
      bank: "revolut",
      amount: -9.99,
      note: "",
    },
    {
      id: "t15",
      date: "2026-04-10",
      merchant: "Freelance client",
      category: null,
      bank: "bbva",
      amount: 650.0,
      note: "Invoice #42",
      income: true,
    },
    {
      id: "t16",
      date: "2026-04-09",
      merchant: "Decathlon",
      category: "health",
      bank: "santander",
      amount: -45.0,
      note: "Running shoes",
    },
    {
      id: "t17",
      date: "2026-04-08",
      merchant: "Carrefour",
      category: "groceries",
      bank: "bbva",
      amount: -112.3,
      note: "",
    },
    {
      id: "t18",
      date: "2026-04-07",
      merchant: "Uber",
      category: "transport",
      bank: "revolut",
      amount: -8.4,
      note: "",
    },
  ];

  const insights = [
    {
      id: "i1",
      kind: "warning",
      icon: "alert-triangle",
      title: "Subscriptions are creeping up",
      body: "You're 41% over budget on subscriptions this month. Three charges from Netflix, Spotify, and Apple Music total €34.97 — consider a family bundle to save ~€8/mo.",
      action: "Review subscriptions",
      savings: 8,
      time: "2h ago",
    },
    {
      id: "i2",
      kind: "positive",
      icon: "trending-up",
      title: "You saved €180 more than last month",
      body: "Your April savings rate is 24% of income — a new high for 2026. At this pace you'll hit your €10k goal by November.",
      action: "See savings plan",
      time: "6h ago",
    },
    {
      id: "i3",
      kind: "suggestion",
      icon: "sparkles",
      title: "Move €500 to your ING savings",
      body: "Your BBVA checking sits €820 above the buffer you usually need. Moving €500 to ING Orange earns ~€11/yr more interest.",
      action: "Move €500",
      time: "1d ago",
    },
    {
      id: "i4",
      kind: "neutral",
      icon: "calendar",
      title: "3 bills due next week",
      body: "Iberdrola (€84.20), Movistar (€45.00), and Gym Pro (€39.90). Total €169.10 — you have plenty in BBVA to cover.",
      action: "Schedule payments",
      time: "1d ago",
    },
  ];

  const spendByMonth = [
    // last 6 months: income, expense
    { m: "Nov", in: 3120, out: 2880 },
    { m: "Dec", in: 3120, out: 3340 },
    { m: "Jan", in: 3890, out: 2740 },
    { m: "Feb", in: 3240, out: 2910 },
    { m: "Mar", in: 3240, out: 2620 },
    { m: "Apr", in: 3890, out: 2395 },
  ];

  return {
    banks,
    availableBanks,
    categories,
    transactions,
    insights,
    spendByMonth,
  };
})();
